# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#
---
include:
  - board: nice_nano
    shield: tbk_mini_left
    cmake-args: -DBOARD_REVISION=2.0.0
  - board: nice_nano
    shield: tbk_mini_right
    cmake-args: -DBOARD_REVISION=2.0.0
  - board: nice_nano
    shield: tbk_mini_dongle
    cmake-args: -DBOARD_REVISION=2.0.0
  # Recovery builds: flash once to wipe persistent settings/bonds, then flash normal builds above.
  - board: nice_nano
    shield: tbk_mini_left
    cmake-args: -DBOARD_REVISION=2.0.0 -DCONFIG_ZMK_SETTINGS_RESET_ON_START=y
    artifact-name: tbk_mini_left_reset
  - board: nice_nano
    shield: tbk_mini_right
    cmake-args: -DBOARD_REVISION=2.0.0 -DCONFIG_ZMK_SETTINGS_RESET_ON_START=y
    artifact-name: tbk_mini_right_reset
  - board: nice_nano
    shield: tbk_mini_dongle
    cmake-args: -DBOARD_REVISION=2.0.0 -DCONFIG_ZMK_SETTINGS_RESET_ON_START=y
    artifact-name: tbk_mini_dongle_reset

